[package]
name = "tomato"
version = "0.1.0"
authors = ["Jean-Loup Adde <jean-loup.adde@juanwolf.fr>"]

[dependencies]
clap = "2.6.0"
pbr  = "1.0.1"
toml = "0.4.10"
dirs = "1.0.4"
serde = "1.0.83"
serde_derive = "1.0.83"
